version: '2'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '9000'
    links:
      - postgres
    restart: on-failure
  postgres:
    image: postgres
    ports:
      - '5432'
    environment:
      - POSTGRES_DB=socialview
      - POSTGRES_PASSWORD=password
    restart: on-failure
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
   ports:
     - '80'
   depends_on:
     - server
