name: raxa
dependencies:
  browser: any
  di: ">=0.0.39 <0.1.0"
  mongo_dart: ">=0.1.41 <0.2.0"
  RestLibrary:
    git: https://github.com/Pajn/RestLibrary.git
  yaml: ">=1.0.0+2 <2.0.0"
dev_dependencies:
  guinness: ">=0.1.7 <1.0.0"
  mock: ">=0.11.0+1 <0.12.0"
